//! Developer tooling. Run as `cargo xtask <command>`.
//!
//! * `check`    — fmt check, clippy (-D warnings), all tests (the quality gate used by CI)
//! * `licenses` — write `docs/THIRD_PARTY_LICENSES.md` from `cargo metadata`
//! * `fixtures` — write the programmatic fixtures to `target/fixtures`
//! * `bench`    — release-mode performance measurements (see docs/PERFORMANCE.md)
//! * `fetch-ocr-models [dir]` — download + verify the OCR models (explicit, opt-in network use)
//! * `icons`    — regenerate `assets/icons` (PNG, ICO, ICNS) from the vector logo
//! * `dist [--with-ocr-models]` — release build and an *unsigned* distribution folder (macOS:
//!   `.app` bundle); the flag downloads, verifies and bundles the OCR models
//!
//! Nothing here publishes, uploads, signs or notarises anything.

mod bundle;
mod icons;
mod ocr_models;

use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map_or_else(|| PathBuf::from("."), Path::to_path_buf)
}

fn cargo(args: &[&str]) -> Result<(), String> {
    let status = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
        .args(args)
        .current_dir(root())
        .status()
        .map_err(|e| format!("could not run cargo: {e}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("`cargo {}` failed ({status})", args.join(" ")))
    }
}

fn check() -> Result<(), String> {
    cargo(&["fmt", "--all", "--", "--check"])?;
    cargo(&[
        "clippy",
        "--workspace",
        "--all-targets",
        "--",
        "-D",
        "warnings",
    ])?;
    cargo(&["test", "--workspace"])
}

fn licenses() -> Result<(), String> {
    let out = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
        .args(["metadata", "--format-version", "1", "--locked"])
        .current_dir(root())
        .output()
        .map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err("cargo metadata failed".into());
    }
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).map_err(|e| e.to_string())?;
    let mut rows: Vec<(String, String, String, String)> = v["packages"]
        .as_array()
        .map(|a| a.as_slice())
        .unwrap_or_default()
        .iter()
        .filter(|p| !p["source"].is_null())
        .map(|p| {
            (
                p["name"].as_str().unwrap_or("?").to_string(),
                p["version"].as_str().unwrap_or("?").to_string(),
                p["license"].as_str().unwrap_or("NOT DECLARED").to_string(),
                p["repository"].as_str().unwrap_or("").to_string(),
            )
        })
        .collect();
    rows.sort();
    let mut md = String::from(
        "# Third-party components\n\n\
         Generated by `cargo xtask licenses` from `Cargo.lock`. This lists every third-party crate\n\
         in the dependency graph for **all** target platforms (including crates only used on\n\
         Windows/macOS/Linux). It is an inventory, **not** a legal notice bundle: before any\n\
         distribution the full licence texts and required copyright notices must be assembled and\n\
         reviewed (see docs/DEPENDENCIES.md for the components that need special attention).\n\n\
         | Crate | Version | Licence (SPDX as declared) | Repository |\n|---|---|---|---|\n",
    );
    for (n, ver, l, r) in &rows {
        md.push_str(&format!("| {n} | {ver} | {l} | {r} |\n"));
    }
    let path = root().join("docs/THIRD_PARTY_LICENSES.md");
    std::fs::write(&path, md).map_err(|e| e.to_string())?;
    println!("wrote {} ({} crates)", path.display(), rows.len());
    Ok(())
}

/// Environment for the dist build. On Windows/MSVC the C runtime is linked statically, so the
/// program does not need the Visual C++ redistributable on the target machine.
fn dist_rustflags() -> Option<String> {
    if !cfg!(all(windows, target_env = "msvc")) {
        return None;
    }
    let mut f = std::env::var("RUSTFLAGS").unwrap_or_default();
    if !f.contains("crt-static") {
        if !f.is_empty() {
            f.push(' ');
        }
        f.push_str("-C target-feature=+crt-static");
    }
    Some(f)
}

fn dist(with_ocr_models: bool) -> Result<(), String> {
    let mut build = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()));
    build
        .args(["build", "--profile", "dist", "-p", "bergpdf"])
        .current_dir(root());
    if let Some(flags) = dist_rustflags() {
        build.env("RUSTFLAGS", flags);
    }
    let status = build
        .status()
        .map_err(|e| format!("could not run cargo: {e}"))?;
    if !status.success() {
        return Err(format!("the dist build failed ({status})"));
    }
    let (os, arch) = (std::env::consts::OS, std::env::consts::ARCH);
    let exe = if os == "windows" {
        "bergpdf.exe"
    } else {
        "bergpdf"
    };
    let bin = root().join("target/dist").join(exe);
    if !bin.exists() {
        return Err(format!("{} not found", bin.display()));
    }
    let version = env!("CARGO_PKG_VERSION");
    let dir = root()
        .join("dist")
        .join(format!("bergpdf-{version}-{os}-{arch}"));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    if os == "macos" {
        bundle::write_app_bundle(
            &dir,
            &bin,
            Some(&root().join("assets/icons/bergpdf.icns")),
            version,
        )
        .map_err(|e| e.to_string())?;
    } else {
        std::fs::copy(&bin, dir.join(exe)).map_err(|e| e.to_string())?;
        // Icons for packagers (Windows .ico for the installer/shortcut, PNG for Linux .desktop).
        for f in ["bergpdf.ico", "bergpdf.png"] {
            std::fs::copy(root().join("assets/icons").join(f), dir.join(f))
                .map_err(|e| e.to_string())?;
        }
    }
    for f in [
        "README.md",
        "docs/THIRD_PARTY_LICENSES.md",
        "docs/DEPENDENCIES.md",
    ] {
        let src = root().join(f);
        if src.exists() {
            let name = Path::new(f).file_name().unwrap_or_default();
            std::fs::copy(&src, dir.join(name)).map_err(|e| e.to_string())?;
        }
    }
    if with_ocr_models {
        // Next to the program on Windows/Linux; inside the bundle on macOS. The app looks in both.
        let models = if os == "macos" {
            dir.join("BergPDF.app/Contents/Resources/ocr-models")
        } else {
            dir.join("ocr-models")
        };
        ocr_models::fetch_into(&models)?;
        std::fs::write(models.join("NOTICE-OCR.txt"), pdf_ocr::MODEL_NOTICE)
            .map_err(|e| e.to_string())?;
        println!("OCR models bundled in {}", models.display());
        println!(
            "WARNING: the redistribution terms of the model weights are unverified (docs/DECISIONS.md D-023)."
        );
    }
    println!("unsigned distribution folder: {}", dir.display());
    println!("(not signed, not notarised, not an installer — see docs/PLATFORM_CHECKLIST.md)");
    Ok(())
}

fn main() -> ExitCode {
    let cmd = std::env::args().nth(1).unwrap_or_default();
    let r = match cmd.as_str() {
        "check" => check(),
        "licenses" => licenses(),
        "fixtures" => cargo(&[
            "run",
            "-q",
            "-p",
            "test-support",
            "--example",
            "gen_fixtures",
            "--",
            "target/fixtures",
        ]),
        "bench" => cargo(&["run", "--release", "-p", "pdf-engine", "--example", "bench"]),
        "fetch-ocr-models" => ocr_models::fetch(std::env::args().nth(2).map(PathBuf::from)),
        "icons" => icons::write_all(&root().join("assets/icons")).map_err(|e| e.to_string()),
        "dist" => {
            let flag = std::env::args().nth(2);
            match flag.as_deref() {
                None => dist(false),
                Some("--with-ocr-models") => dist(true),
                Some(other) => Err(format!("unknown option {other}")),
            }
        }
        _ => {
            eprintln!(
                "usage: cargo xtask <check|licenses|fixtures|bench|icons|fetch-ocr-models [dir]|dist [--with-ocr-models]>"
            );
            return ExitCode::from(2);
        }
    };
    match r {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    /// `Packager.toml` repeats the version; it must not drift from the workspace's.
    #[test]
    fn the_installer_config_has_the_workspace_version() {
        let cfg = std::fs::read_to_string(super::root().join("Packager.toml")).unwrap();
        let line = cfg
            .lines()
            .find(|l| l.starts_with("version = "))
            .expect("Packager.toml has a version");
        assert_eq!(
            line.trim_start_matches("version = ").trim_matches('"'),
            env!("CARGO_PKG_VERSION"),
            "update Packager.toml when the workspace version changes"
        );
    }
}
